#!/usr/bin/bash

# arg1 -> base dir
# arg2 -> session name (default is "base")


echo "creating new tmux session"
getopts s: session
sess=$OPTARG
getopts b: base_dir
base=$OPTARG


echo session: $sess
echo $base
if [ -z "$sess" ]
then
    sess="base"
fi
echo $sess

thing=$(tmux ls | grep attached)
echo "$thing"

#IFS=':' read -ra boop <<< "$thing"
#for i in "${ADDR[@]}"; do
#    echo "$i"
#    echo "here"
#done

#(tmux a -t "$sess" || tmux new-sess -s "$sess")



